name: duty-machine-action
description: 'save web article as issue'
runs:
  # using: 'docker'
  # image: 'Dockerfile'
  # using: 'node12'
  # main: 'perform.js'
  using: "composite"
  steps:
    - id: install-system-deps
      shell: bash
      run: |
        set -xe
        echo ttf-mscorefonts-installer msttcorefonts/accepted-mscorefonts-eula select true | sudo debconf-set-selections
        echo ttf-mscorefonts-installer msttcorefonts/present-mscorefonts-eula note | sudo debconf-set-selections
        sudo apt-get install -y language-pack-en ttf-mscorefonts-installer
        sudo apt-get install -y ca-certificates fonts-arphic-ukai \
          fonts-arphic-uming fonts-freefont-ttf fonts-ipafont-gothic \
          fonts-kacst fonts-liberation fonts-noto fonts-thai-tlwg \
          gconf-service libappindicator1 libappindicator3-1 libasound2 \
          libatk-bridge2.0-0 libatk1.0-0 libc6 libcairo2 libcups2 libdbus-1-3 \
          libexpat1 libfontconfig1 libgbm1 libgcc1 libgconf-2-4 \
          libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libnss3 \
          libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 \
          libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 \
          libxi6 libxrandr2 libxrender1 libxss1 libxtst6 lsb-release procps \
          ttf-wqy-microhei ttf-wqy-zenhei wget x11-apps x11-xkb-utils x11vnc \
          xdg-utils xfonts-100dpi xfonts-75dpi xfonts-cyrillic \
          xfonts-scalable xvfb
        sudo fc-cache -fv
    - id: install-node-deps
      shell: bash
      run: |
        set -xe
        cd ${{ github.action_path }}
        npm install
    - id: run
      shell: bash
      run: |
        set -xe
        cd ${{ github.action_path }}
        # Xvfb -ac :99 -screen 0 1280x1024x16 > /dev/null 2>&1 &
        export DISPLAY=":99.0"
        # export DEBUG='*'
        xvfb-run --auto-servernum node perform.js
branding:
  icon: 'camera'
  color: 'purple'
